export const EMPLOYEE_LOGIN_REQUEST = 'EMPLOYEE_LOGIN_REQUEST'
export const EMPLOYEE_LOGIN_SUCCESS = 'EMPLOYEE_LOGIN_SUCCESS'
export const EMPLOYEE_LOGIN_FAIL = 'EMPLOYEE_LOGIN_FAIL'
export const EMPLOYEE_LOGOUT = 'EMPLOYEE_LOGOUT'

export const CREATE_CARD_REQUEST = 'CREATE_CARD_REQUEST'
export const CREATE_CARD_REQUEST_SUCCESS = 'CREATE_CARD_REQUEST_SUCCESS'
export const CREATE_CARD_REQUEST_FAIL = 'CREATE_CARD_REQUEST_FAIL'