export const ORGANIZATION_LOGIN_REQUEST = 'ORGANIZATION_LOGIN_REQUEST'
export const ORGANIZATION_LOGIN_SUCCESS = 'ORGANIZATION_LOGIN_SUCCESS'
export const ORGANIZATION_LOGIN_FAIL = 'ORGANIZATION_LOGIN_FAIL'
export const ORGANIZATION_LOGOUT = 'ORGANIZATION_LOGOUT'

export const ORGANIZATION_REGISTER_REQUEST = 'ORGANIZATION_REGISTER_REQUEST'
export const ORGANIZATION_REGISTER_SUCCESS = 'ORGANIZATION_REGISTER_SUCCESS'
export const ORGANIZATION_REGISTER_FAIL = 'ORGANIZATION_REGISTER_FAIL'

export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST'
export const CREATE_EMPLOYEE_REQUEST_SUCCESS = 'CREATE_EMPLOYEE_REQUEST_SUCCESS'
export const CREATE_EMPLOYEE_REQUEST_FAIL = 'CREATE_EMPLOYEE_REQUEST_FAIL'

export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST'
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_SUCCESS'
export const ORGANIZATION_DETAILS_FAIL = 'ORGANIZATION_DETAILS_FAIL'
export const ORGANIZATION_DETAILS_RESET = 'ORGANIZATION_DETAILS_RESET'

export const GET_ALL_EMPLOYEE_REQUEST = 'GET_ALL_EMPLOYEE_REQUEST'
export const GET_ALL_EMPLOYEE_SUCCESS = 'GET_ALL_EMPLOYEE_SUCCESS'
export const GET_ALL_EMPLOYEE_FAIL = 'GET_ALL_EMPLOYEE_FAIL'

export const GET_ALL_CARDS_REQUEST = 'GET_ALL_CARDS_REQUEST'
export const GET_ALL_CARDS_SUCCESS = 'GET_ALL_CARDS_SUCCESS'
export const GET_ALL_CARDS_FAIL = 'GET_ALL_CARDS_FAIL'
